apiVersion: v1
kind: Service
metadata:
  name: kubecon-demo-filestash-preview
spec:
  ports:
    - name: tcp-kubecon-demo-filestash
      port: 9002
      targetPort: 8334
  selector:
    app.kubernetes.io/name: kubecon-demo-filestash
  type: ClusterIP
